 // This code was autogenerated from nrpc.proto, do not edit.
package pb
import (
	"context"
	"log"
	"time"
	"google.golang.org/protobuf/proto"
	"github.com/nats-io/nats.go"
	"github.com/nats-rpc/nrpc"
)
type Client struct {
	nc      nrpc.NatsConn
	defaultEncoding string
	defaultTimeout time.Duration
}
func NewClient(nc nrpc.NatsConn) *Client {
	c := Client{
		nc: nc,
		defaultEncoding: "protobuf",
		defaultTimeout: 5*time.Second,
	}
	return &c
}
func (c *Client) SetEncoding(encoding string) {
	c.defaultEncoding = encoding
}
func (c *Client) SetTimeout(t time.Duration) {
	c.defaultTimeout = t
}
