version: '3'
services:
  # server:
  #   container_name: go-template
  #   build:
  #     context: .
  #     dockerfile: DockerFile
  #   ports:
  #   - 8080:8080
  #   volumes: 
  #     - .:/code
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
  rabbitmq:
    image: "rabbitmq"
    ports:
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
  mongodb:
    hostname: mongodb
    image: mongo
    volumes:
      - ./mongo-volume:/data/db
    #entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest" ]
    ports:
      - "27017:27017"
    restart: always
  # elasticsearch:
  #   hostname: elasticsearch
  #   image: stabenfeldt/elasticsearch-marvel
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   links:
  #     - mongodb:mongodb
  #   volumes:
  #     - ./db-service/elasticsearch/logging.yml:/etc/elasticsearch/logging.yml
  #   restart: always
    