// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package models

import (
	"time"

	"github.com/usk81/generic"
)

type Hub struct {
	ID         string       `db:"id" json:"id"`
	Name       string       `db:"name" json:"name"`
	LocationID string       `db:"location_id" json:"location_id"`
	CreatedAt  generic.Time `db:"created_at" json:"created_at"`
	UpdatedAt  generic.Time `db:"updated_at" json:"updated_at"`
	DeletedAt  generic.Time `db:"deleted_at" json:"deleted_at"`
	Json       []byte       `db:"json" json:"json"`
}

type Team struct {
	ID         string       `db:"id" json:"id"`
	Name       string       `db:"name" json:"name"`
	Type       string       `db:"type" json:"type"`
	HubID      string       `db:"hub_id" json:"hub_id"`
	LocationID string       `db:"location_id" json:"location_id"`
	CreatedAt  generic.Time `db:"created_at" json:"created_at"`
	UpdatedAt  generic.Time `db:"updated_at" json:"updated_at"`
	DeletedAt  generic.Time `db:"deleted_at" json:"deleted_at"`
}

type User struct {
	ID        string       `db:"id" json:"id"`
	Name      string       `db:"name" json:"name"`
	Type      string       `db:"type" json:"type"`
	TeamID    string       `db:"team_id" json:"team_id"`
	CreatedAt generic.Time `db:"created_at" json:"created_at"`
	UpdatedAt generic.Time `db:"updated_at" json:"updated_at"`
	DeletedAt generic.Time `db:"deleted_at" json:"deleted_at"`
}


type Bicycle struct {
	ID        string    `json:"id,omitempty" bson:"id,omitempty" db:"id"`
	Type      string    `json:"type,omitempty" bson:"type,omitempty" db:"type"`
	CreatedAt time.Time `json:"created_at,omitempty" bson:"created_at,omitempty" db:"created_at"`
}
