// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package models

import (
	"database/sql"

	"github.com/jackc/pgtype"
)

type Hub struct {
	ID   int64          `db:"id" json:"id"`
	Name pgtype.Text    `db:"name" json:"name"`
	Bio  sql.NullString `db:"bio" json:"bio"`
}

type User struct {
	ID   int64          `db:"id" json:"id"`
	Name pgtype.Text    `db:"name" json:"name"`
	Bio  sql.NullString `db:"bio" json:"bio"`
}
