// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package models

import (
	"context"

	"github.com/jackc/pgtype"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DeleteUser(ctx context.Context, id pgtype.Text) (*User, error)
	FindUserByID(ctx context.Context, id pgtype.Text) (*User, error)
	GetFunction(ctx context.Context) ([]*GetFunctionRow, error)
	GetListUser(ctx context.Context, arg GetListUserParams) ([]*User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
