// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateHub(ctx context.Context, arg CreateHubParams) (*Hub, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (*Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DeleteHub(ctx context.Context, id string) (*Hub, error)
	DeleteTeam(ctx context.Context, id string) (*Team, error)
	DeleteUser(ctx context.Context, id string) (*User, error)
	FindHubByID(ctx context.Context, id string) (*Hub, error)
	FindTeamByID(ctx context.Context, id string) (*Team, error)
	FindUserByID(ctx context.Context, id string) (*User, error)
	GetListHub(ctx context.Context, arg GetListHubParams) ([]*Hub, error)
	GetListTeam(ctx context.Context, arg GetListTeamParams) ([]*Team, error)
	GetListUser(ctx context.Context, arg GetListUserParams) ([]*User, error)
	SearchHub(ctx context.Context, dollar_1 pgtype.Text) ([]*Hub, error)
	SearchTeam(ctx context.Context, dollar_1 pgtype.Text) ([]*Team, error)
	UpdateHub(ctx context.Context, arg UpdateHubParams) (*Hub, error)
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (*Team, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
