// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: team.sql

package models

import (
	"context"

	"github.com/jackc/pgtype"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams(id,name)
values($1,$2)
Returning id, name, type, hub_id, location_id, created_at, updated_at, deleted_at
`

type CreateTeamParams struct {
	ID   pgtype.Text `db:"id" json:"id"`
	Name pgtype.Text `db:"name" json:"name"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (*Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam, arg.ID, arg.Name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.HubID,
		&i.LocationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const deleteTeam = `-- name: DeleteTeam :one
DELETE from teams where id = $1
Returning id, name, type, hub_id, location_id, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteTeam(ctx context.Context, id pgtype.Text) (*Team, error) {
	row := q.db.QueryRowContext(ctx, deleteTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.HubID,
		&i.LocationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const findTeamByID = `-- name: FindTeamByID :one
SELECT id, name, type, hub_id, location_id, created_at, updated_at, deleted_at FROM teams
WHERE id = $1 LIMIT 1
`

func (q *Queries) FindTeamByID(ctx context.Context, id pgtype.Text) (*Team, error) {
	row := q.db.QueryRowContext(ctx, findTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.HubID,
		&i.LocationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getListTeam = `-- name: GetListTeam :many
SELECT id, name, type, hub_id, location_id, created_at, updated_at, deleted_at FROM teams
offset $1 limit $2
`

type GetListTeamParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

func (q *Queries) GetListTeam(ctx context.Context, arg GetListTeamParams) ([]*Team, error) {
	rows, err := q.db.QueryContext(ctx, getListTeam, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.HubID,
			&i.LocationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams set name = $1
where id = $2
Returning id, name, type, hub_id, location_id, created_at, updated_at, deleted_at
`

type UpdateTeamParams struct {
	Name pgtype.Text `db:"name" json:"name"`
	ID   pgtype.Text `db:"id" json:"id"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (*Team, error) {
	row := q.db.QueryRowContext(ctx, updateTeam, arg.Name, arg.ID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.HubID,
		&i.LocationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}
