// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TeamRepository is an autogenerated mock type for the TeamRepository type
type TeamRepository struct {
	mock.Mock
}

type mockConstructorTestingTNewTeamRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewTeamRepository creates a new instance of TeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTeamRepository(t mockConstructorTestingTNewTeamRepository) *TeamRepository {
	mock := &TeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
