version: "3.4"

services:
  # generate_go:
  #   image: gen-go
  #   build:
  #     context: ../
  #     target: protoc_gen_go
  #     dockerfile: ./developments/proto.Dockerfile
  #   volumes:
  #     - "../proto/:/proto/"
  #     - "../pb/:/pb/"
  #     - "../docs/:/go/docs/"
  #     - "./gen-go.sh:/gen-go.sh"
  #     - "../internal/models:/go/internal/models"
  #   entrypoint: /gen-go.sh

  generate_sqlc:
    image: kjconroy/sqlc
    working_dir: /src/
    volumes:
      - "../database/:/src/"
      - "../internal/models/:/models/"
      - "./sqlc.yaml:/src/sqlc.yaml"
    command: ["generate"]
