/*
  ____            _   _           _
 / ___|   _   _  | | | |   __ _  | |__    _   _   ___
 \___ \  | | | | | | | |  / _` | | '_ \  | | | | / __|
  ___) | | |_| | | | | | | (_| | | |_) | | |_| | \__ \
 |____/   \__, | |_| |_|  \__,_| |_.__/   \__,_| |___/
          |___/

*/
// * Code generated by protoc-gen-syllabus. DO NOT EDIT.
// * versions:
// * - protoc-gen-syllabus (devel)
// * - protoc                   v3.6.1
// * source: auth

package pb
