/* *
                      _
  ___   _   _   ___  | |_    ___    _ __ ___
 / __| | | | | / __| | __|  / _ \  | '_ ` _ \
| (__  | |_| | \__ \ | |_  | (_) | | | | | | |
 \___|  \__,_| |___/  \__|  \___/  |_| |_| |_|

*/
// * Code generated by protoc-gen-custom. DO NOT EDIT.
// * versions:
// * - protoc-gen-custom (devel)
// * - protoc                   v3.14.0
// * source: auth

package pb

const (
	AuthService_Login          = "/auth.AuthService/Login"
	AuthService_ForgotPassword = "/auth.AuthService/ForgotPassword"
	AuthService_VerifyOTP      = "/auth.AuthService/VerifyOTP"
	AuthService_ResetPassword  = "/auth.AuthService/ResetPassword"
	AuthService_ChangePassword = "/auth.AuthService/ChangePassword"
)
