/* *
                      _
  ___   _   _   ___  | |_    ___    _ __ ___
 / __| | | | | / __| | __|  / _ \  | '_ ` _ \
| (__  | |_| | \__ \ | |_  | (_) | | | | | | |
 \___|  \__,_| |___/  \__|  \___/  |_| |_| |_|

*/
// * Code generated by protoc-gen-custom. DO NOT EDIT.
// * versions:
// * - protoc-gen-custom (devel)
// * - protoc                   v3.14.0
// * source: hub

package pb

const (
	HubService_GetHubByID = "/hub.HubService/GetHubByID"
	HubService_CreateHub  = "/hub.HubService/CreateHub"
	HubService_GetList    = "/hub.HubService/GetList"
	HubService_UpdateHub  = "/hub.HubService/UpdateHub"
)
