/*
                       _
   ___   _   _   ___  | |_    ___    _ __ ___
  / __| | | | | / __| | __|  / _ \  | '_ ` _ \
 | (__  | |_| | \__ \ | |_  | (_) | | | | | | |
  \___|  \__,_| |___/  \__|  \___/  |_| |_| |_|

*/
// * Code generated by protoc-gen-custom. DO NOT EDIT.
// * versions:
// * - protoc-gen-custom (devel)
// * - protoc                   v3.14.0
// * source: nrpc

package pb

func (x SubjectRule) FromString(str string) SubjectRule {
	switch str {
	case SubjectRule_COPY.String():
		return SubjectRule_COPY
	case SubjectRule_TOLOWER.String():
		return SubjectRule_TOLOWER
	}
	return SubjectRule(0)
}
