// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: search.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SearchTeamHubRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SearchTeamHubRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SearchTeamHubRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SearchTeamHubRequestMultiError, or nil if none found.
func (m *SearchTeamHubRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SearchTeamHubRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Q

	if len(errors) > 0 {
		return SearchTeamHubRequestMultiError(errors)
	}

	return nil
}

// SearchTeamHubRequestMultiError is an error wrapping multiple validation
// errors returned by SearchTeamHubRequest.ValidateAll() if the designated
// constraints aren't met.
type SearchTeamHubRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SearchTeamHubRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SearchTeamHubRequestMultiError) AllErrors() []error { return m }

// SearchTeamHubRequestValidationError is the validation error returned by
// SearchTeamHubRequest.Validate if the designated constraints aren't met.
type SearchTeamHubRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchTeamHubRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchTeamHubRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchTeamHubRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchTeamHubRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchTeamHubRequestValidationError) ErrorName() string {
	return "SearchTeamHubRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SearchTeamHubRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchTeamHubRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchTeamHubRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchTeamHubRequestValidationError{}

// Validate checks the field values on SearchTeamHubResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SearchTeamHubResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SearchTeamHubResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SearchTeamHubResponseMultiError, or nil if none found.
func (m *SearchTeamHubResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SearchTeamHubResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTeams() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SearchTeamHubResponseValidationError{
						field:  fmt.Sprintf("Teams[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SearchTeamHubResponseValidationError{
						field:  fmt.Sprintf("Teams[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SearchTeamHubResponseValidationError{
					field:  fmt.Sprintf("Teams[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetHubs() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SearchTeamHubResponseValidationError{
						field:  fmt.Sprintf("Hubs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SearchTeamHubResponseValidationError{
						field:  fmt.Sprintf("Hubs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SearchTeamHubResponseValidationError{
					field:  fmt.Sprintf("Hubs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SearchTeamHubResponseMultiError(errors)
	}

	return nil
}

// SearchTeamHubResponseMultiError is an error wrapping multiple validation
// errors returned by SearchTeamHubResponse.ValidateAll() if the designated
// constraints aren't met.
type SearchTeamHubResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SearchTeamHubResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SearchTeamHubResponseMultiError) AllErrors() []error { return m }

// SearchTeamHubResponseValidationError is the validation error returned by
// SearchTeamHubResponse.Validate if the designated constraints aren't met.
type SearchTeamHubResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchTeamHubResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchTeamHubResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchTeamHubResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchTeamHubResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchTeamHubResponseValidationError) ErrorName() string {
	return "SearchTeamHubResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SearchTeamHubResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchTeamHubResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchTeamHubResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchTeamHubResponseValidationError{}
