name: Branch rules

on: 
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Base branch format
        id: base_branch_format
        uses: actions/github-script@v6
        with:
          script: |
            const regex = 'feature/*';
            const headBranch = context.payload.pull_request.head.ref;
            if(!headBranch.match(regex)) {
                github.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.payload.number,
                  body: 'Source branch must be feature/*',
                });
            }