name: Go Package

on:
  pull_request: 
    branches:
      - main
    types: [opened]
  label: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
          check-latest: true

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
      
      - name: Lint
        uses: reviewdog/action-golangci-lint@v2