name: Issue rules
on:
  pull_request: 
    branches:
      - main
    types: [opened, reopened, ready_for_review]

jobs:
  check_linked_issues:
    runs-on: ubuntu-latest
    outputs:
      isConvert: ${{ steps.limit_pull_request.outputs.isConvert }}
    steps:
      - name: check linked issues
        uses: nearform/github-action-check-linked-issues@v1
        id: check_linked_issues
        with:
          exclude-branches: "release/**, dependabot/**"