name: Issue rules
on:
  pull_request: 
    branches:
      - main
    types: [opened, reopened, ready_for_review]

jobs:
  verify_linked_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Verify linked Issue
        id: verify_linked_issue
        uses: hattan/verify-linked-issue-action@v1.1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}