name: Pull request rules

on:
  pull_request: 
    branches:
      - main
    types: [opened, reopened, ready_for_review]

jobs:
  limit_pull_request:
    runs-on: ubuntu-latest
    outputs:
      isConvert: ${{ steps.limit_pull_request.outputs.isConvert }}
    steps:
      - name: Limit pull request 
        id: limit_pull_request
        uses: actions/github-script@v6
        env:
          PR_LIMIT: 4
        with:
          script: |
            const { PR_LIMIT } = process.env;
            const result = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              base: 'main',
            });
            const num = result.data.filter(pull => !pull.draft).length;
            if(num <= PR_LIMIT) return;
            core.setOutput('isConvert', true);

      - name: Convert to draft
        uses: octokit/graphql-action@v2.x
        id: convert_pr_to_daft
        if: ${{ steps.limit_pull_request.outputs.isConvert }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          query: |
            mutation ConvertToDraft {
              convertPullRequestToDraft(input: {clientMutationId: "github-action", pullRequestId: "${{ github.event.pull_request.node_id }}"}) {
                __typename
              }
            }
